services:
  - type: web
    name: khandelwal-sons
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CALLMEBOT_APIKEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: OWNER_PASSWORD
        value: "shivay123"
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: OWNER_WHATSAPP
        value: "919321782424"
